
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /mnt/data/Projects/Big/autoinsights:/app

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - /mnt/data/Projects/Big/autoinsights:/app
