version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app
