services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run ui/app.py
      - backend
    volumes:
      - .:/app
